"""drop jid unique constraint and merge duplicates

Revision ID: 0c9a3e68a72d
Revises: a1f2b95f1375
Create Date: 2026-04-08 18:13:49.564952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9a3e68a72d'
down_revision: Union[str, None] = 'a1f2b95f1375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conversations_jid_clinic', 'whatsapp_conversations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_conversations_jid_clinic', 'whatsapp_conversations', ['jid', 'clinic_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
