"""add media_url and reply_to_id to messages

Revision ID: a1f2b95f1375
Revises: ec3b2c8f02e7
Create Date: 2026-04-08 14:23:02.341682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f2b95f1375'
down_revision: Union[str, None] = 'ec3b2c8f02e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('media_url', sa.Text(), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'whatsapp_messages', 'whatsapp_messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_messages', type_='foreignkey')
    op.drop_column('whatsapp_messages', 'reply_to_id')
    op.drop_column('whatsapp_messages', 'media_url')
    # ### end Alembic commands ###
