"""add whatsapp_sessions table

Revision ID: c4c7e926902f
Revises: 00055855236b
Create Date: 2026-04-08 12:00:36.130537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c7e926902f'
down_revision: Union[str, None] = '00055855236b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('connecting', 'qr', 'connected', 'disconnected', name='whatsappsessionstatus'), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_sessions_clinic_id'), 'whatsapp_sessions', ['clinic_id'], unique=False)
    op.create_index('ix_whatsapp_sessions_clinic_status', 'whatsapp_sessions', ['clinic_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whatsapp_sessions_clinic_status', table_name='whatsapp_sessions')
    op.drop_index(op.f('ix_whatsapp_sessions_clinic_id'), table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    # ### end Alembic commands ###
