"""add conversations and messages tables

Revision ID: ec3b2c8f02e7
Revises: c4c7e926902f
Create Date: 2026-04-08 14:09:35.068916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3b2c8f02e7'
down_revision: Union[str, None] = 'c4c7e926902f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('jid', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['whatsapp_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jid', 'clinic_id', name='uq_conversations_jid_clinic')
    )
    op.create_index('ix_wa_conv_clinic_session_last', 'whatsapp_conversations', ['clinic_id', 'session_id', 'last_message_at'], unique=False)
    op.create_index('ix_wa_conv_patient', 'whatsapp_conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_clinic_id'), 'whatsapp_conversations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_jid'), 'whatsapp_conversations', ['jid'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'DOCUMENT', 'AUDIO', 'VIDEO', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='messagestatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wa_msg_conv_timestamp', 'whatsapp_messages', ['conversation_id', 'timestamp'], unique=False)
    op.create_index('ix_wa_msg_message_id', 'whatsapp_messages', ['wa_message_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_messages_clinic_id'), 'whatsapp_messages', ['clinic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_clinic_id'), table_name='whatsapp_messages')
    op.drop_index('ix_wa_msg_message_id', table_name='whatsapp_messages')
    op.drop_index('ix_wa_msg_conv_timestamp', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_conversations_jid'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_clinic_id'), table_name='whatsapp_conversations')
    op.drop_index('ix_wa_conv_patient', table_name='whatsapp_conversations')
    op.drop_index('ix_wa_conv_clinic_session_last', table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    # ### end Alembic commands ###
