"""add tracking tables

Revision ID: fab078af044e
Revises: 0c9a3e68a72d
Create Date: 2026-04-08 21:46:46.913971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab078af044e'
down_revision: Union[str, None] = '0c9a3e68a72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('include_value', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'pipeline_stage', name='uq_mapping_clinic_stage')
    )
    op.create_index(op.f('ix_event_mappings_clinic_id'), 'event_mappings', ['clinic_id'], unique=False)
    op.create_table('tracking_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('META', 'GOOGLE_ADS', 'GA4', 'GTM', 'SNAPCHAT', 'TIKTOK', name='trackingplatform'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'platform', name='uq_tracking_clinic_platform')
    )
    op.create_index(op.f('ix_tracking_integrations_clinic_id'), 'tracking_integrations', ['clinic_id'], unique=False)
    op.create_table('conversion_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('META', 'GOOGLE_ADS', 'GA4', 'GTM', 'SNAPCHAT', 'TIKTOK', name='trackingplatform'), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.Enum('WHATSAPP_MESSAGE', 'DEAL_STAGE_CHANGE', 'APPOINTMENT_STATUS', 'FORM_SUBMISSION', name='triggertype'), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='eventstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_event_clinic_created', 'conversion_events', ['clinic_id', 'created_at'], unique=False)
    op.create_index('ix_conv_event_clinic_platform_status', 'conversion_events', ['clinic_id', 'platform', 'status'], unique=False)
    op.create_index(op.f('ix_conversion_events_clinic_id'), 'conversion_events', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_event_id'), 'conversion_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversion_events_event_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_clinic_id'), table_name='conversion_events')
    op.drop_index('ix_conv_event_clinic_platform_status', table_name='conversion_events')
    op.drop_index('ix_conv_event_clinic_created', table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_index(op.f('ix_tracking_integrations_clinic_id'), table_name='tracking_integrations')
    op.drop_table('tracking_integrations')
    op.drop_index(op.f('ix_event_mappings_clinic_id'), table_name='event_mappings')
    op.drop_table('event_mappings')
    # ### end Alembic commands ###
